######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 18 17:12:48 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DrawingArea.h \
           DrawingThread.h \
           DrawingWindow.h

SOURCES += DrawingArea.cpp \
           DrawingThread.cpp \
           DrawingWindow.cpp \
           hello.cc
